# Custom and Advanced Configuration for Sidekiq.
# http://manuelvanrijn.nl/sidekiq-heroku-redis-calc/

:concurrency: <%= Integer(ENV["SIDEKIQ_CONCURRENCY"] || 2) %> # Bumping Redis Connections to 50 allows bumping this.
:queues:
  - default
  - mailer
